# Site settings
title: Doh's Dev Blog
email: dosio0102@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: Doh Blog

# Social icons
facebook: Dohwan Kim
linkedin: username
github: kimdohwan
deviantart: username
codepen: username

footer: © Taken theme

# Build settings
markdown: kramdown
